version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .dev_env
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: deportes-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
